### PR TITLE
minor bug in compare array functionality

### PR DESCRIPTION
**Pull request by rb004f**
I believe it was meant to do element comparison here and not array point comparison

### CODE REVIEW

**Comment by ccoffrin** [comment]
I did not have a chance to check in detail, but yes this looks like a bug.  We will need a test to make sure it does not come back.  Do you know of a specific kind of situation where this comes up?

**Comment by rb004f** [comment]
I should give credit to Rivera for seeing this bug. It would only crop up if we had a key,value pair where value is an array and the entries in the array are not numbers.  I can't think of a situation where we would have had data of that format. Should be easy to add a test for it though

**Comment by ccoffrin** [comment]
I think I need a bit more help to identify a case that is an issue for you. I tried this,
```
    @testset "array test" begin
        mn_data = InfrastructureModels.replicate(generic_si_network_data, 2, Set{String}())

        nw_1 = mn_data["nw"]["1"]
        nw_2 = mn_data["nw"]["2"]

        nw_1["dict"]["b"] = ["A","B","C"]
        nw_2["dict"]["b"] = ["A","B","D"]

        @test InfrastructureModels.compare_dict(nw_1, nw_2)
    end
```
The behavior appears to be correct in both cases when the two arrays are the same and different.  It appears that the Julia semantics for `!=` are too recurse on the data structures and see if they match, so the output appears to be correct to me. 

Maybe this is the case you had in mind?
```
nw_1["dict"]["b"] = ["A","B",2]
nw_2["dict"]["b"] = ["A","B",2.00000001]
InfrastructureModels.compare_dict(nw_1, nw_2)
```
In this situation the spirit of `compare_dict` is that it should return `true`, as 2 is close to 2.00000001 but it will return false in this case because it does not recurse on the elements of the array.

**Comment by rb004f** [comment]
The first case is what I had in mind.  I was under the impression that julia semantics for '!=' was at the object level and not the element level.  It looks like object level uses the '===' syntax.  But your second example is a good one and perhaps we want to account for a more explicit element comparison...

**Comment by ccoffrin** [comment]
My original goal for this function just to improve how we can do unit testing.  I did not intend it to be used in more general contexts outside of tests.  So if we have a specific test use case that needs this additional feature I'll add a test for it. If not, I would prefer to pass on adding this feature in the interest of not needing to maintain a specific feature that may not be in use by any tests.  Would that be ok?

**Comment by rb004f** [comment]
@ccoffrin I agree, we have an implementation that is technically correct and it is only used for tests.  But, since it is there, it is open season for any of our users to use.  And, I will note that it is a "hidden" quadratic loop (or worse) that should be linear.

if you look at the block of code as it is now, you can see that it loops through each entry of the array. If the entry is a number, then it does the element comparison, which is fine. If it is not a number, then it will, according to the syntax of ```!=```  check each element of the array in a redundant fashion.  Thus, if each element of the array is a string, ```v1 != v2``` will check every element in the array (in a duplicate fashion) implicitly making for a quadratic  loop.  Moreover, if the elements of the array are something more exotic like some sort of nested arrays, this would really blow up the run time since it would be checking everything over and over.

So, while I agree that without a use case, there is limited utility in patching this.  However, it was one those hidden "computational blow up" implementations, where, should we (or one of the package users) ever have a use case in the future with this type of comparison requirement, it will be really hard to track down since it is so subtle.  I would recommend making this change to save headaches later.  The change boils down to making ```v1 != v2``` become ```v1[i] != v2[i]``` which is semantically equivalent, but makes the runtime O(n) instead of O(n^2). Your call.

```
elseif isa(v1, Array)
            if length(v1) != length(v2)
                return false
            end
            for i in 1:length(v1)
                if isa(v1[i], Number)
                    if !_compare_numbers(v1[i], v2[i])
                        return false
                    end
                else
                    if v1 != v2
                        #println(v1, " ", v2)
                        return false
                    end
                end
            end
```

**Comment by ccoffrin** [comment]
Fixed in #83

I was not able to think of a test that would directly test the performance point, so I used the proposed floating point comparison correctness test as a proxy.

**Pull request closed without merging**
