### PR TITLE
AbstractInfrastructureModel and Support Functions

### PR DESCRIPTION
**Pull request by ccoffrin**
@kaarthiksundar, at your request here is my proposal for InfrastructureModels shared functionalities.  Everything seems to be working well in some branches of PowerModels.  Before merging this I would like you to try using them in GasModels to make sure the features suits your needs.

New features:
- Standardization of InfrastructureModel data type fields, `AbstractInfrastructureModel`, `@im_fields` 
- Generalized data type initialization, `InitializeInfrastructureModel`
- Standardization of helper functions, `ids`, `ref`, `var`, `con`, `sol`, `nw_ids`, `nws`
- Generalized ref building, `build_ref` (with updated `ref_extentions` api)
- Standardization of optimization call, `optimize_model!`
- Standardization of solution building, `build_result`, `build_solution` 

Steps for a downstream package to use these features:

- Make the root model type a subtype of `AbstractInfrastructureModel` like so, `abstract type AbstractPowerModel <: _IM.AbstractInfrastructureModel end`
- Update the fields macro, like so, `_IM.@def pm_fields begin PowerModels.@im_fields end`
- Overload the `instantiate_model` function with required specialization, e.g.,
```
function instantiate_model(data::Dict{String,<:Any}, model_type::Type, build_method; kwargs...)
    return _IM.instantiate_model(data, model_type, build_method, ref_add_core!, _pm_global_keys; kwargs...)
end
```
- Overload the `build_ref` function with required specialization, e.g.,
```
function build_ref(data::Dict{String,<:Any}; ref_extensions=[])
    return _IM.build_ref(data, ref_add_core!, _pm_global_keys, ref_extensions=ref_extensions)
end
```
- Update `ref_extentions` to the new API (details in https://github.com/lanl-ansi/PowerModels.jl/issues/668)
- Import helper functions from InfrastructureModels like so `import InfrastructureModels: ids, ref, var, con, sol, nw_ids, nws, optimize_model!, @im_fields`
- Re-export helper functions for your users convenience, `export ids, ref, var, con, sol, nw_ids, nws, optimize_model!`

CC @rb004f @tasseff @pseudocubic

### CODE REVIEW

**Comment by ccoffrin** [comment]
Great.  Before I merge this into master and tag it, I think it would be prudent to make at least a test branch of GasModels that uses these features, so that we can avoid making breaking changes shortly after the initial release of these features.

**Comment by kaarthiksundar** [comment]
@pseudocubic Can you create a branch from master and make sure this works. If not, I will do it after Wednesday.

**Comment by pseudocubic** [comment]
@kaarthiksundar I think should have some time tomorrow to do that

**Comment by ccoffrin** [comment]
Thanks!  If this gets delayed to the end of the week that's fine as well.

**Comment by pseudocubic** [comment]
@rb004f @kaarthiksundar  in GasModels in `instantiate_model` it looks like support is needed for kwargs for `build_method`

There are two points in the current implementation that cause our current tests to fail:

1. All kwargs from `instantiate_model` are passed to `InitializeInfrastructureModel`, but `InitializeInfrastructureModel` does not support arbitrary kwargs (there is no `kwargs...` in the function call)
2. No kwargs are passed to `build_model`

This shows up in `run_ne`. A potential solution to this on our end is to move `obj_normalization` to the data structure instead of a kwarg. This is what I would probably suggest, what are your preferences?

CC @ccoffrin

**Comment by kaarthiksundar** [comment]
@pseudocubic i vote for pushing the objective normalization as an optional data in the Matgas format.

**Comment by pseudocubic** [comment]
@ccoffrin how do we copy things to the solution dict using this pattern, e.g. base_flow, base_pressure, etc. like baseMVA in powermodels?

**Comment by rb004f** [comment]
In the gasmodels branch "examples" for the specific case of the ne formulation, I am moving in the direction of having those cases having the coefficients of the objective function normalized in the data file rather than doing the normalization as an optional parameter in pos_ne... my main reason for doing this is that third parties can use the data files for independent reproduction of the results.  So, I may drop that field from this specific objective function in a couple weeks once I am done with doing that.  That being said, it might be nice to have a general utility function to automatically normalize any objective function....

**Comment by ccoffrin** [comment]
@pseudocubic the current solution is to overload the `solution_preprocessor` function like so, https://github.com/lanl-ansi/PowerModels.jl/blob/im-sol/src/core/solution.jl#L2

**Comment by ccoffrin** [comment]
@rb004f, I may have misunderstood something.  What you are talking about sounds like a feature request that is independent of the features discussed here?  If so, I suggest to open an issue and work on that once this collection of features is solidified.

**Comment by rb004f** [comment]
Referring to comment from @pseudocubic 

"This shows up in run_ne. A potential solution to this on our end is to move obj_normalization to the data structure instead of a kwarg. This is what I would probably suggest, what are your preferences?"

I was indicating that obj_normalization may disappear as an optional field in the next couple of weeks, which may render this question moot.  However, I did want to capture the idea that having general support for normalization of objective coefficients might be a nice to have down the road.

**Comment by ccoffrin** [comment]
Also, I am not 100% clear on what `obj_normalization` is, but maybe it can be moved to the `settings` field?

**Comment by rb004f** [comment]
In network expansion, often the cost coefficients for new piplines are big numbers.  To get better numeric stability, we typically divide these by 1e9 or something like that.  The benefit of having obj_normalization allows(ed) the user to specify real costs but normalize those costs by some constant. The con is that this is a hidden parameter which can make it hard for others to reproduce a result soley from an input file. So, at least for the benchmarks, I am going to express the objective function coefficients in normalized values which eliminates the need to have the obj_normalization parameter in the near term.  The consistent way to do this would be to have a base_cost parameter (like base_pressure) which is provided in the input file to do normalization of costs like we do for pressure and other physical parameters.

**Comment by ccoffrin** [comment]
On a related note, I learned that objective scaling is quite key in making the SDP relaxation work in PowerSystem, but there was not clean way to support an objective rescaling in PowerModels.  My thought for how to resolve this was to add an objective scaling parameter to the data model (which is 1.0 by default), when the user can specify to rescale the objective in the JuMP model.  https://github.com/lanl-ansi/PowerModels.jl/issues/368

**Comment by rb004f** [comment]
Yes, I suspected this might be a more fundamental capability we would want to support.  If it makes sense, maybe it should be supported in InfrastructureModels?

**Comment by ccoffrin** [comment]
For the solution I have in mind, the parameter would enter during objective creation.  So I think it's best to address in each packages locally for now.

**Comment by pseudocubic** [comment]
@ccoffrin can you remind me how i include a variable transformation for the solution? The actual variable is pressure squared , and i want to return pressure

**Comment by ccoffrin** [comment]
The new convention is to report variables as they are in the model by default.  So the default semantics would be to return pressure squared.  To solve the issue of projecting solutions back to the data model standards you want a model-specific post-processor.  In PowerModels I called this, `sol_data_model!`.

The generic template is here,
https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/solution.jl#L175

A specific implementation for sqrt is here,
https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/shared.jl#L108

**Comment by pseudocubic** [comment]
@ccoffrin all tests pass in GasModels after upgrading to these tools

**Comment by ccoffrin** [comment]
Great!  Thanks a lot for confirming.  I'll write some tests for these features in this package and then do a release.

**Pull request merged**
