### PR TITLE
ADD: Functions for checking existence of time series data and obtaining the number of possible networks

### PR DESCRIPTION
**Pull request by tasseff**

### CODE REVIEW

**Comment by tasseff** [comment]
Upon merging, tagging a new patch version would be great.

**Comment by ccoffrin** [comment]
Looks good.  Do the tests cover both the case of non-multinetwork and single point multi network?  As I recall both cases are already in tests, just make sure to call `get_num_networks` in both cases.

**Comment by tasseff** [comment]
Yes, all cases are being covered. Want me to merge and tag a new version?

**Comment by ccoffrin** [comment]
Sure, go for it!

**Pull request merged**
